POST https://trello-like-board-api.vercel.app/api/item
Content-Type: application/json

{
    "title": "Second task",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "status": "Done",
    "user": "User 2"
}

###

GET https://trello-like-board-api.vercel.app/api/items
Content-Type: application/json

###

PUT https://trello-like-board-api.vercel.app/api/item/640274b4a5eb3427128927d3
Content-Type: application/json

{
    "title": "First task",
    "description": "In tempor consequat sapien, vitae eleifend nisi interdum et.",
    "status": "To Do",
    "user": "User 1"
}

###

DELETE  https://trello-like-board-api.vercel.app/api/item/640277ffa5eb3427128927d7
Content-Type: application/json